config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :boats do
    resources :reviews, except: %i[index show destroy]
    resources :bookings, only: %i[create]
    resources :reviews, only: %i[create update]

    collection do
      post :calculate_total_price, to: 'bookings#calculate_total_price'
    end
  end

  get '/dashboard', to: 'users#dashboard', as: :user_dashboard
  get '/booking_requests', to: 'users#booking_request_decision', as: :booking_requests
  post '/bookings/:id/accept', to: 'bookings#accept', as: 'booking_accept'
  post '/bookings/:id/reject', to: 'bookings#reject', as: 'booking_reject'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/boat.rb
class Boat < ApplicationRecord
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  has_many :bookings, dependent: :destroy
  has_many_attached :images
  has_many :reviews, dependent: :destroy
  belongs_to :user
end

app/models/booking.rb
class Booking < ApplicationRecord
  attr_accessor :date_range, :message

  belongs_to :user
  belongs_to :boat
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :boat
  belongs_to :user

  validates :rating, presence: true
  validates :content, presence: true
  validates :boat_id, uniqueness: { scope: :user_id, message: "was already reviewed" }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boats, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :booking_requests
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: %i[show edit update destroy]

  def index
    @boats = Boat.all
    @markers = @boats.geocoded.map do |boat|
      {
        lat: boat.latitude,
        lng: boat.longitude
      }
    end
  end

  def show
    @reviews = Review.where(boat_id: @boat.id)
    @review = Review.new
    @booking = Booking.new()
  end

  def new
    @boat = Boat.new
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.user = current_user
    @boat.save
    redirect_to boats_path
  end

  def edit
  end

  def update
    @boat.update(boat_params)
    redirect_to boat_path(@boat), notice: 'Listing was successfully updated.'
  end

  def destroy
    @boat.destroy
    redirect_to user_dashboard_path, notice: 'Listing was successfully destroyed.'
  end

  private

  def set_boat
    @boat = Boat.find(params[:id])
  end

  def boat_params
    params.require(:boat).permit(
      :name, :length, :width, :height, :location, :price, :capacity, :decks, :crew_required, images: []
    )
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    date_range = booking_params[:date_range].split(" to ")
    @booking = Booking.new(start_date: Date.parse(date_range[0]), end_date: Date.parse(date_range[1]), status: "open")
    @booking.user = current_user
    @booking.boat = Boat.find(params[:boat_id])
    if @booking.save
      flash[:notice] = 'Booking request sent'
      redirect_to boat_path(@booking.boat)
    else
      render 'boats/show'
    end
  end

  def accept
    booking = Booking.find(params[:id])
    booking.update(status: 'accepted')
    redirect_to user_dashboard_path
  end

  def reject
    booking = Booking.find(params[:id])
    booking.update(status: 'rejected')
    redirect_to user_dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:date_range)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_boat, only: %i[create]
  before_action :authenticate_user!, only: [:create]

  def create
    @boat = Boat.find(params[:boat_id])
    # @review = @boat.reviews.new(review_params)
    @review = Review.new(review_params)
    @review.boat = @boat
    @review.user = current_user
    @booking = Booking.new

    if @review.save
      redirect_to boat_path(@boat)
    else
      render "boats/show", status: :unprocessable_entity
    end
  end

  private

  def set_boat
    @boat = Boat.find(params[:boat_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user = current_user
    @boats = @user.boats
    @bookings = current_user.bookings.where(status: "accepted")
    @open_requests_count = Booking.joins(:boat).where(boats: { user_id: @user.id }, status: "open").count
  end

  def booking_request_decision
    @user = current_user
    @boats = @user.boats
    @bookings = Booking.joins(:boat).where(boats: { user_id: @user.id }, status: "open")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_stars(rating)
    return unless rating.present? # Skip rendering if rating is nil or blank

    content_tag(:span, class: 'stars') do
      rating.times do
        concat content_tag(:i, '', class: 'fas fa-star')
      end
    end
  end

end

app/views/boats/edit.html.erb
<div class="boat-form-container">
    <h1 class="boat-form-header">New Boat <i class="fas fa-ship"></i></h1>
    <%= simple_form_for @boat do |f| %>
      <%= f.input :name, label: 'Name', input_html: { class: "boat-form-input" } %>
      <%= f.input :length, label: 'Length (in m)', input_html: { class: "boat-form-input" } %>
      <%= f.input :width, label: 'Width (in m)', input_html: { class: "boat-form-input" } %>
      <%= f.input :height, label: 'Height (in m)', input_html: { class: "boat-form-input" } %>
      <%= f.input :price, label: 'Price per day (in €)', input_html: { class: "boat-form-input" } %>
      <%= f.input :capacity, label: 'Capacity (people)', input_html: { class: "boat-form-input" } %>
      <%= f.input :decks, label: 'Decks (#)', input_html: { class: "boat-form-input" } %>
      <%= f.input :crew_required, label: 'Crew Required', as: :boolean, input_html: { class: "boat-form-input" } %>
      <%= f.input :location,
        input_html: {data: {address_autocomplete_target: "location"}, class: "boat-form-input d-none"},
        wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
      %>
      <%= f.input :images, as: :file, input_html: { multiple: true, class: "boat-form-input" } %>

      <div class="boat-form-actions">
        <%= f.button :submit, class: "boat-form-submit-btn" %>
      </div>
    <% end %>
  </div>
</div>

<%= link_to 'Back', user_dashboard_path %>

app/views/boats/index.html.erb
<div class="container mt-1">
  <div class="row">
    <!-- Boats Cards (2/3 of the page) -->
    <div class="col-md-8">
      <div class="row">
        <% @boats.each do |boat| %>
          <div class="col-md-4 mb-4">
            <div class="card h-100">
              <% if boat.images.attached? %>
                <%= cl_image_tag(boat.images.first.key, width: 300, height: 200, crop: :fill, class: 'card-img-top') %>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= link_to boat.name, boat_path(boat) %></h5>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
     <div style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>

app/views/boats/new.html.erb
<div class="boat-form-container">
    <h1 class="boat-form-header">New Boat <i class="fas fa-ship"></i></h1>
    <%= simple_form_for @boat do |f| %>
      <%= f.input :name, label: 'Name', input_html: { class: "boat-form-input" } %>
      <%= f.input :length, label: 'Length (in m)', input_html: { class: "boat-form-input" } %>
      <%= f.input :width, label: 'Width (in m)', input_html: { class: "boat-form-input" } %>
      <%= f.input :height, label: 'Height (in m)', input_html: { class: "boat-form-input" } %>
      <%= f.input :price, label: 'Price per day (in €)', input_html: { class: "boat-form-input" } %>
      <%= f.input :capacity, label: 'Capacity (people)', input_html: { class: "boat-form-input" } %>
      <%= f.input :decks, label: 'Decks (#)', input_html: { class: "boat-form-input" } %>
      <%= f.input :crew_required, label: 'Crew Required', as: :boolean, input_html: { class: "boat-form-input" } %>
      <%= f.input :location,
        input_html: {data: {address_autocomplete_target: "location"}, class: "boat-form-input d-none"},
        wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
      %>
      <%= f.input :images, as: :file, input_html: { multiple: true, class: "boat-form-input" } %>

      <div class="boat-form-actions">
        <%= f.button :submit, class: "boat-form-submit-btn" %>
      </div>
    <% end %>
  </div>
</div>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<div class="boat-details">
  <div class= "image-card">
    <h1><%= @boat.name %></h1>
    <h4><%= @boat.location %></h4>

    <% if @boat.images.attached? %>
      <div class="boat-images">
        <% @boat.images.each do |image| %>
          <%= cl_image_tag image.key, class: "boat-image" %>
        <% end %>

    <% else %>
      <p>No images attached.</p>
    <% end %>

  <div class="booking-card">
  <h3 data-boat-price="<%= @boat.price %>"><%= @boat.price %> € per day</h3>
  <%= render "bookings/calendar"%>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
  <% end %>
</div>
</div>
</div>

  <div class="boat-description">
    <h2>Specs</h2>
    <div class="specs-container">
      <div class="specs-column">
        <div class="specs-card">
          <i class="fas fa-users"></i>
          <p>Capacity: <%= @boat.capacity %> people</p>
        </div>
        <div class="specs-card">
          <i class="fas fa-ship"></i>
          <p>Decks: <%= @boat.decks %></p>
        </div>
        <div class="specs-card">
          <i class="fas fa-user-friends"></i>
          <p>Crew Required: <%= @boat.crew_required %></p>
        </div>
      </div>
      <div class="specs-column">
        <div class="specs-card">
          <i class="fas fa-ruler-horizontal"></i>
          <p>Length: <%= @boat.length %> meters</p>
        </div>
        <div class="specs-card">
          <i class="fas fa-ruler-vertical"></i>
          <p>Width: <%= @boat.width %> meters</p>
        </div>
        <div class="specs-card">
          <i class="fas fa-ruler-vertical"></i>
          <p>Height: <%= @boat.height %> meters</p>
        </div>
      </div>
    </div>
  </div>


<div class="reviews-section">
  <h2>Reviews</h2>
  <div class="row">
    <% @boat.reviews.each do |review| %>
      <div class="col-md-6">
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title"><strong>Rating:</strong> <%= render_stars(review.rating) %></h5>
            <p class="card-text"><strong>Content:</strong> <%= review.content %></p>
            <p class="card-text"><strong>Created by:</strong> <%= review.user.email %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


   <div class="leave-review">
  <h2>Leave a Review</h2>
  <% if user_signed_in? %>
    <% user_booking_for_this_boat = current_user.bookings.find_by(boat_id: @boat.id) %>
    <% if user_booking_for_this_boat %>

      <% if @review.errors.any? %>
  <div class="alert alert-danger">
    <% @review.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
<% end %>


      <%= render 'reviews/review', boat: @boat, user: current_user %>
    <% else %>
      <p>You can only leave a review for boats you have booked.</p>
    <% end %>
  <% else %>
    <p>Please log in to leave a review.</p>
  <% end %>
</div>

app/views/bookings/_calendar.html.erb
<%= simple_form_for [@boat, @booking], remote: true do |f| %>
  <%= f.input :date_range, label: 'When would you like to rent?', placeholder: 'Pick desired dates', input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :message, label: 'Message', placeholder: 'Leave a message...', input_html: { rows: 4 } %>
  <p>Total Price: €</p>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoatsBoatsBoats</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <div class="content-wrapper">
      <%= render "shared/navbar" %>
      <%= yield %>
    </div>
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    <div class="footer-copyright">
      copyright Boatmania Inc.
    </div>
  </body>
</html>

app/views/pages/boats.html.erb
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
        <%= image_tag (@boat.poster_url), width: 400, class: "img-fluid rounded-start" %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @boat.name %></h5>
        <p class="card-text"><%= @boat.length, @boat.width, @boat.height%></p>
        <p class="card-text"><small class="text-body-secondary"><%= @boat.user%></small></p>
      </div>
    </div>
  </div>
</div>


<%# <div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    Breakfast
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
    Lunch
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">
    Dinner
  </div>
</div> %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url(<%= asset_path("pexels-pirateship.jpg") %>);">
  <div class="container">
    <h1 class="banner-heading">Boats ! Boats ! Boats !</h1>
    <p class="banner-subtext">Select your dream boat from our large collection. <br> Connect to +2500 boats for your every needs</p>
    <% if !user_signed_in? %>
      <a class="btn btn-flat btn-register" href="<%= new_user_registration_path %>">Register</a>
    <% end %>
    <% if user_signed_in? %>
      <a class="btn btn-flat btn-view-boats" href="<%= boats_path %>">View Boats</a>
    <% end %>
  </div>
</div>

app/views/pages/index.html.erb
<%= render "shared/navbar" %>
<ol>
  <% @boats.each do |boat| %>
    <li><%= boat %></li>
  <% end %>
</ol>

app/views/reviews/_review.html.erb
<%= form_for([boat, Review.new], remote: true) do |f| %>
  <div class="form-group rating-dropdown">
  <%= f.select :rating, options_for_select((1..5).map { |num| [num, num] }), { prompt: 'Rating' }, class: 'form-dropdown' %>
</div>
  <div class="form-group">
  <%= f.text_area :content, placeholder: 'Your review content here...', class: 'form-description' %>
</div>
  <div class="form-group">
    <%= f.submit 'Submit Review' %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    copyright Boats Boats Boats
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "undraw_Yacht_re_kkai.png"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", user_dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Boats", boats_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/booking_request_decision.html.erb
<!-- Open Booking Requests Section -->
<div class="open-booking-requests-container">
  <div class="dashboard-header-container">
    <h2 class="dashboard-header">Your Open Booking Requests:</h2>
  </div>
  <% @bookings.each do |booking| %>
    <div class="open-booking-card">
      <div class="open-booking-info-container">
        <span class="open-booking-info"><strong>Boat:</strong> <%= booking.boat.name %></span>
        <span class="open-booking-info"><strong>Start Date:</strong> <%= booking.start_date %></span>
        <span class="open-booking-info"><strong>End Date:</strong> <%= booking.end_date %></span>
        <span class="open-booking-info"><strong>Nights:</strong> <%= (booking.end_date - booking.start_date).to_i %> nights</span>
        <span class="open-booking-info"><strong>Location:</strong> <%= booking.boat.location %></span>
      </div>
      <div class="open-booking-buttons">
        <%= button_to "Accept", booking_accept_path(booking), class: "accept-btn" %>
        <%= button_to "Reject", booking_reject_path(booking), class: "reject-btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/dashboard.html.erb
<div class="dashboard-container">
  <h1>Welcome to Your Dashboard, <%= @user.email %></h1>

  <!-- Toggle Buttons -->
  <div class="dashboard-toggle-buttons">
    <button id="lenderViewBtn" onclick="showLenderView()">Lender View</button>
    <button id="borrowerViewBtn" onclick="showBorrowerView()">Borrower View</button>
  </div>

<!-- Lender View -->
<div id="lenderView">
  <div class="dashboard-header-container">
    <h2 class="dashboard-header"><strong>Manage Your Boats</strong></h2>
    <%= link_to "Create New Boat", new_boat_path, class: "create-boat-btn" %>
  </div>

  <% if @boats.any? %>
    <div class="dashboard-boat-cards-container">
      <% @boats.each do |boat| %>
        <div class="dashboard-boat-card">
          <%= link_to boat_path(boat) do %>
            <% if boat.images.attached? && boat.images.first.present? %>
              <%= cl_image_tag(boat.images.first.key, width: 300, height: 200, crop: :fill, class: 'dashboard-boat-card-image') %>
            <% end %>
            <div class="dashboard-boat-card-body">
              <h3 class="dashboard-boat-card-title">
                <%= boat.name %>
                <div class="dashboard-boat-card-actions-container">
                  <%= link_to edit_boat_path(boat) do %>
                    <i class="fas fa-edit dashboard-edit-boat-icon" title="Edit Boat"></i>
                  <% end %>
                  <%= button_to boat_path(boat), method: :delete, data: { confirm: 'Are you sure you want to delete this boat?' }, class: "dashboard-delete-boat-btn" do %>
                    <i class="fas fa-trash dashboard-delete-boat-icon" title="Delete Boat"></i>
                  <% end %>
                </div>
              </h3>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>You have no boats.</p>
  <% end %>
</div>

    <div class="dashboard-header-container">
      <h2 class="dashboard-header">Your Accepted Bookings:</h2>
      <%= link_to "Open Requests (#{@open_requests_count})", booking_requests_path, class: "open-requests-btn" %>
    </div>
    <% @bookings.select { |booking| booking.status == "accepted" }.each do |booking| %>
      <div class="booking-card">
        <div class="booking-info">
          <span class="booking-boat-name"><strong>Boat:</strong> <%= booking.boat.name %></span>
          <span class="booking-dates">
            <strong>Start Date:</strong> <%= booking.start_date %> -
            <strong>End Date:</strong> <%= booking.end_date %>
          </span>
          <span class="booking-nights">
            <strong>Nights:</strong> <%= (booking.end_date - booking.start_date).to_i %> nights
          </span>
          <span class="booking-location">
            <strong>Location:</strong> <%= booking.boat.location %>
          </span>
        </div>
        <!-- Add any additional information or action buttons here -->
      </div>
    <% end %>
</div>
</div>